// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smfifdvbdupcuymlnhro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZmlmZHZiZHVwY3V5bWxuaHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTczMDcsImV4cCI6MjA2OTQ3MzMwN30.Wl4pancYDhSoBlpG5nNbp0L65QLYQXKgbz8D4QBoNdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});